apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-demand-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-demand-model
  template:
    metadata:
      labels:
        app: retail-demand-model
    spec:
      containers:
      - name: retail-demand-model
        image: retail-demand-model:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
